apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: mdhack/solar-system:7-cd38fca702a819e004109029eb1d93d06b05636f
        name: solar-system
        ports: 
        - containerPort: 80
